# Generated by Django 3.1.7 on 2021-05-24 00:23

import WifiMonitor.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimelapseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name=WifiMonitor.forms.DateInput)),
                ('end', models.DateField(verbose_name=WifiMonitor.forms.DateInput)),
            ],
        ),
    ]
