# Generated by Django 3.1.7 on 2021-05-25 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WifiMonitor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimelapseModel',
        ),
    ]
