# Generated by Django 3.1.7 on 2021-05-25 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WifiMonitor', '0003_departament'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departament',
            new_name='Departments',
        ),
    ]
