# coding: utf-8

"""
    primecore

    API Definition of primecore

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class InlineResponse200(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'first': 'float',
        'last': 'float',
        'count': 'float',
        'access_points': 'list[AccessPointObject]'
    }

    attribute_map = {
        'first': 'first',
        'last': 'last',
        'count': 'count',
        'access_points': 'accessPoints'
    }

    def __init__(self, first=None, last=None, count=None, access_points=None):
        """
        InlineResponse200 - a model defined in Swagger
        """

        self._first = None
        self._last = None
        self._count = None
        self._access_points = None

        if first is not None:
          self.first = first
        if last is not None:
          self.last = last
        if count is not None:
          self.count = count
        if access_points is not None:
          self.access_points = access_points

    @property
    def first(self):
        """
        Gets the first of this InlineResponse200.

        :return: The first of this InlineResponse200.
        :rtype: float
        """
        return self._first

    @first.setter
    def first(self, first):
        """
        Sets the first of this InlineResponse200.

        :param first: The first of this InlineResponse200.
        :type: float
        """

        self._first = first

    @property
    def last(self):
        """
        Gets the last of this InlineResponse200.

        :return: The last of this InlineResponse200.
        :rtype: float
        """
        return self._last

    @last.setter
    def last(self, last):
        """
        Sets the last of this InlineResponse200.

        :param last: The last of this InlineResponse200.
        :type: float
        """

        self._last = last

    @property
    def count(self):
        """
        Gets the count of this InlineResponse200.

        :return: The count of this InlineResponse200.
        :rtype: float
        """
        return self._count

    @count.setter
    def count(self, count):
        """
        Sets the count of this InlineResponse200.

        :param count: The count of this InlineResponse200.
        :type: float
        """

        self._count = count

    @property
    def access_points(self):
        """
        Gets the access_points of this InlineResponse200.

        :return: The access_points of this InlineResponse200.
        :rtype: list[AccessPointObject]
        """
        return self._access_points

    @access_points.setter
    def access_points(self, access_points):
        """
        Sets the access_points of this InlineResponse200.

        :param access_points: The access_points of this InlineResponse200.
        :type: list[AccessPointObject]
        """

        self._access_points = access_points

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, InlineResponse200):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
