# coding: utf-8

"""
    primecore

    API Definition of primecore

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class MetricsObjectMetricsDataValues(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'x_value': 'float',
        'y_values': 'MetricsObjectMetricsDataYValues'
    }

    attribute_map = {
        'x_value': 'XValue',
        'y_values': 'YValues'
    }

    def __init__(self, x_value=None, y_values=None):
        """
        MetricsObjectMetricsDataValues - a model defined in Swagger
        """

        self._x_value = None
        self._y_values = None

        if x_value is not None:
          self.x_value = x_value
        if y_values is not None:
          self.y_values = y_values

    @property
    def x_value(self):
        """
        Gets the x_value of this MetricsObjectMetricsDataValues.

        :return: The x_value of this MetricsObjectMetricsDataValues.
        :rtype: float
        """
        return self._x_value

    @x_value.setter
    def x_value(self, x_value):
        """
        Sets the x_value of this MetricsObjectMetricsDataValues.

        :param x_value: The x_value of this MetricsObjectMetricsDataValues.
        :type: float
        """

        self._x_value = x_value

    @property
    def y_values(self):
        """
        Gets the y_values of this MetricsObjectMetricsDataValues.

        :return: The y_values of this MetricsObjectMetricsDataValues.
        :rtype: MetricsObjectMetricsDataYValues
        """
        return self._y_values

    @y_values.setter
    def y_values(self, y_values):
        """
        Sets the y_values of this MetricsObjectMetricsDataValues.

        :param y_values: The y_values of this MetricsObjectMetricsDataValues.
        :type: MetricsObjectMetricsDataYValues
        """

        self._y_values = y_values

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, MetricsObjectMetricsDataValues):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
